#!/usr/bin/env bash

# Logging stuff
function log_warn()    { echo -e "\x1B[31m\x1B[4mWarning\x1B[24m\x1B[39m: $@"; }
function log_error()   { echo -e "\x1B[31m\x1B[4mError\x1B[24m\x1B[39m: $@"; }
function log_ok()      { echo -e "\x1B[32m==> \x1B[39m$@"; }
function log_success() { echo -e "\x1B[32m$@\x1B[39m"; }
function log_fail()    { echo -e "\x1B[31m$@\x1B[39m"; }
function log_header()  { echo -e "\x1B[4m$@\x1B[24m"; }
function log_subhead() { echo -e "\x1B[1m$@\x1B[22m"; }
function log_info()    { echo -e "\x1B[33m==> \x1B[39m$@"; }

# http://stackoverflow.com/a/3232082
function confirm() {
  # call with a prompt string or use a default
  read -r -p "${1:-Continue?} [y/N] " response
  case $response in
    [yY][eE][sS]|[yY]) 
      true
      ;;
    *)
      false
      ;;
  esac
}

function symlink() {
  ln -fs $1 $2
  log_info "Symlinked $1 -> $2"
}

